language: java

jdk:
  - openjdk11

before_cache:
  - rm -rf $HOME/.m2/repository/**/*-SNAPSHOT

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.m2/wrapper"

script:
  - "./mvnw package"

notifications:
  email: true
